---
- hosts: democa
  remote_user: root
  vars_files:
    - common_env.yml
    - democa_env.yml
    #  include the results of password_generator.yml
    - secrets_env.yml
  roles:
    - common
    - basic
    - democa
  tasks:
