---
- hosts: democa
  remote_user: root
  vars_files:
    - "{{ configdir }}common_env.yml"
    - "{{ configdir }}democa_env.yml"
    #  include the results of password_generator.yml
    - secrets_env.yml
  roles:
    - common
    - { role: basic, when: not private_ds_address == private_ca_address }
    - democa
  tasks:
