---

- hosts: 127.0.0.1
  connection: local
  vars:
    - passwd_generator_file: secrets_env.yml
  tasks:

    - name: "check if {{ passwd_generator_file }} file exists"
      stat:
        path: "{{ passwd_generator_file }}"
      register: pass_file

    - name: "create new {{ passwd_generator_file }} file"
      command: "cp -p {{ passwd_generator_file }}.PLACEHOLDER {{ passwd_generator_file }}"
      when: pass_file.stat.exists == False

    - name: "set permissions of {{ passwd_generator_file }}"
      file:
        path: "{{ passwd_generator_file }}"
        state: file
        mode: 0600

    - include_tasks: passwd_generator.yml
      with_items:
        - rsync_secret
        - mysql_root_password
        - mariadb_root_password
        - postgresql_root_password
        - oa4mp_server_db_pw
        - oa4mp_server_keystore_pw
        - democa_pass
