---

### enabled and disabled services

enabled_services:
 - myproxy-server
 - postfix

### general package dependencies, installed in the basic role

extra_packages:
 - postfix

### backup constants

backup_packages:
 - rsync

### myproxy constants:

myproxy_packages:
 - myproxy-server
 - myproxy-admin
 - myproxy-doc
 - globus-simple-ca
