---
- name: "Add private CA address to hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ private_ca_fqdn }}$'
    line: "{{ private_ca_address }} {{ private_ca_fqdn }}"
    state: present
  when: not private_ds_address == private_ca_address

- name: "Add private DS address to hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ private_ds_fqdn }}$'
    line: "{{ private_ds_address }} {{ private_ds_fqdn }}"
    state: present
  when: not private_ds_address == private_ca_address
