---

# basic configuration

- import_tasks: hosts.yml
- import_tasks: nameserver.yml
- import_tasks: yum_squid.yml

# include tasks to execute

- import_tasks: postfix.yml
- import_tasks: rsyslog.yml

- import_tasks: canet_ca.yml
- import_tasks: rsync_sshkey.yml
- import_tasks: backup.yml

- import_tasks: myproxy.yml
- import_tasks: hostcreds.yml
- import_tasks: democa_tarball.yml

# list of enabled services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
