---
### general packages that should be present

general_packages:
  - libselinux-python
  - net-tools
  - bind-utils
  - mailx
  - sysstat
  - ntp
  - iptables-services
  - ipset-service
  - patch
  - xinetd
  - nscd
  - authconfig
  - smartmontools
  - ipmitool

### list of enabled and disabled services

enabled_services:
  - ntpd
  - ipset
  - iptables
  - ip6tables

disabled_services:
  - NetworkManager
  - wpa_supplicant
  - firewalld

### additional repository information

epelrpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epelkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
