---

# This task has a counterpart in the cafrontend role where passwords are enabled
# for the backend. Here they are again disabled.
# Note that the basic role sets the overall policy to disabled.

# disable ssh access for root from backends
- name: remove ssh access for root from backend
  lineinfile:
    dest: "/etc/security/access.conf"
    regexp: "^[#]*(.*: root : {{ private_ca_network }}.*)$"
    backrefs: yes
    line: '#\1'
    backup: yes
  when: not private_ca_address == private_ds_address

# Add specific block for password-based logins from the CA
- name: disable ssh password logins for backend
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} backend CA password policy"
    insertafter: EOF
    backup: yes
    block: |
        Match address {{ private_ca_network }}
           # Enable pw authN here when updating the ssh keys
           PasswordAuthentication no
           PermitRootLogin without-password
  # sshd handler is defined in the common role
  notify: restart sshd
  when: not private_ca_address == private_ds_address
