---

# check on the CA node periodically and send email if it is down

- name: copy ca_checker to sbin
  template:
    src: ca_checker.sh.j2
    dest: "{{ ca_checker_script }}"
    owner: root
    group: root
    mode: 0755
    backup: yes

- name: add cron job to run ca_checker script
  file:
     src: "{{ ca_checker_script }}"
     dest: /etc/cron.hourly/ca_checker.cron
     owner: root
     state: link

# also regularly ping CA machine to prevent ARP problems

- name: add cron job to ping CA and optionally run CA checker
  cron:
    name: "ping CA every minute to remember MAC and run ca_checker on failure"
    cron_file: ping_ca
    user: root
    minute: "*"
    job: "{ ! /usr/bin/ping -c1 -w1 {{ private_ca_address }} > /dev/null 2>&1 || test -f {{ ca_checker_using_backup_file }}; } && {{ ca_checker_script }}"
