---

# configure trust and key stores
# NOTE: we need to run dep-tomcat and oa4mp-server first, to have the tomcat
# user and to have /var/www/server/conf

- name: create private trusted certificates dir and set attributes
  file:
    path: "{{ oa4mp_server_certificates_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  when: priv_creds.stat.exists

- name: copy private trusted certificates to oa4mp server dir
  shell: "cp -f {{ private_creds_capath }}/* {{ oa4mp_server_certificates_dir }}"
  when: priv_creds.stat.exists

- name: add private myproxy credentials to keystore
  command: openssl pkcs12 -export -in "{{ myproxy_cert }}" -inkey "{{ myproxy_key }}" -out "{{ oa4mp_server_keystore }}" -name privcred -CApath "{{ private_creds_capath }}" -chain -passout "pass:{{ oa4mp_server_keystore_pw }}"
  when: priv_creds.stat.exists

- name: add the right permission to the key store
  file:
    path: "{{ oa4mp_server_keystore }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0400
  when: priv_creds.stat.exists
