---

### config additional repos

- import_tasks: addn-repos.yml

### other config required for backend CA

- import_tasks: ca-sshd.yml
- import_tasks: ca-backup.yml
- import_tasks: ca_checker.yml

### services required for DS itself

- import_tasks: java.yml
- import_tasks: tomcat.yml
- import_tasks: httpd.yml
- import_tasks: shib.yml
- import_tasks: mariadb.yml
#- import_tasks: postgresql.yml

### config for DS itself

- import_tasks: rsyncd.yml
  when: rsync_hosts is defined
- import_tasks: mysql-backup.yml
- import_tasks: oa4mp-server.yml
- import_tasks: webroot.yml

### host certs, certdirs and truststores for tomcat and apache

- import_tasks: hostcreds-tomcat.yml
- import_tasks: hostcreds-apache.yml

### enable services

- name: enable and start services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
