---

# Install MySQL Server

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items: "{{ mysql_packages }}"
  register: mysql_installation

# Start MySQL Server

- name: Start the MySQL service
  service: name=mysqld state=started enabled=yes

# Configure root password (but only on fresh mysql installations)

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_installation.changed

# check OA4MP Server DB

- name: Create OA4MP Server DB
  mysql_db: 
    name: "{{ oa4mp_server_db }}" 
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: server_db

- name: copy oa4mp server sql script
  template: 
    src: oa4mp-server-mysql.sql.j2
    dest: /tmp/oa4mp-server-mysql.sql
  when: server_db.changed

- name: execute oa4mp server sql script
  mysql_db: 
    state: import
    name: all 
    target: /tmp/oa4mp-server-mysql.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: server_db.changed

- name: remove oa4mp server sql script
  file:
    path: /tmp/oa4mp-server-mysql.sql
    state: absent
  when: server_db.changed
