---

# Install MariaDB/MySQL Server

- name: install MariaDB/MySQL
  yum:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_installation

- name: make a link to the connector
  file:
    src: "{{ mysql_connector_path }}/{{ mysql_connector }}"
    dest: "{{ catalina_home }}/lib/{{ mysql_connector }}"
    owner: root
    group: root
    state: link

# Start MariaDB/MySQL Server

- name: start the MariaDB/MySQL service
  service: name={{ mysql_service }} state=started enabled=yes

# Configure root password (but only on fresh installations)

- name: update MariaDB/MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_installation.changed

# check OA4MP Server DB
# NOTE: we cannot just check the DB without creating, but to prevent import from
# running every time we have to run 'present', hence we cannot postpone creating
# the database until we run import. Creating the DB in the script is therefore
# not actually needed nor done.

- name: create OA4MP Server DB
  mysql_db:
    name: "{{ oa4mp_server_db }}"
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: server_db
  when: mysql_root_password is defined

- name: update MariaDB/MySQL oa4mp user account
  mysql_user:
    name: "{{ oa4mp_server_db_user }}"
    host: "{{ item }}"
    password: "{{ oa4mp_server_db_pw }}"
    priv: "{{ oa4mp_server_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_root_password is defined

- name: copy oa4mp server sql script
  template:
    src: oa4mp-server-mysql.sql.j2
    dest: /tmp/oa4mp-server-mysql.sql
  when: server_db is defined and server_db.changed

- name: execute oa4mp server sql script
  mysql_db:
    state: import
    name: all
    target: /tmp/oa4mp-server-mysql.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: server_db is defined and server_db.changed

- name: remove oa4mp server sql script
  file:
    path: /tmp/oa4mp-server-mysql.sql
    state: absent
  when: server_db is defined and server_db.changed
