---

# backup mysql database

- name: copy mysql-dump.sh to sbin
  copy:
    src: mysql-dump.sh
    dest: /usr/local/sbin/mysql-dump.sh
    owner: root
    group: root
    mode: 0755

- name: copy mysql-restore.sh to sbin
  copy:
    src: mysql-restore.sh
    dest: /usr/local/sbin/mysql-restore.sh
    owner: root
    group: root
    mode: 0755

- name: add cron job to run mysql-dump.sh script
  file:
    src: /usr/local/sbin/mysql-dump.sh
    dest: /etc/cron.daily/mysql-backup
    owner: root
    state: link
