---

- name: add mariadb.org repo
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.5/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: 1

# Install MariaDB/MySQL Server

- name: install MariaDB/MySQL
  yum:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_installation

# Note: we don't install the connector since we rely on the shipped versions

# Start MariaDB/MySQL Server

- name: start the MariaDB/MySQL service
  service: name={{ mysql_service }} state=started enabled=yes

# Configure root password (but only on fresh installations)

- name: update MariaDB/MySQL root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  no_log: true
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_installation.changed

- name: drop test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  when: mysql_root_password is defined

# check OA4MP Server DB
# NOTE: we cannot just check the DB without creating, but to prevent import from
# running every time we have to run 'present', hence we cannot postpone creating
# the database until we run import. Creating the DB in the script is therefore
# not actually needed nor done.

- name: create OA4MP Server DB
  mysql_db:
    name: "{{ oa4mp_server_db }}"
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  register: server_db
  when: mysql_root_password is defined

- name: update MariaDB/MySQL oa4mp user account
  mysql_user:
    name: "{{ oa4mp_server_db_user }}"
    host: "{{ item }}"
    password: "{{ oa4mp_server_db_pw }}"
    priv: "{{ oa4mp_server_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_root_password is defined

- name: copy oa4mp server sql script
  template:
    src: oa4mp-server-mysql.sql.j2
    dest: /tmp/oa4mp-server-mysql.sql
  when: server_db is defined and server_db.changed

- name: execute oa4mp server sql script
  mysql_db:
    state: import
    name: all
    target: /tmp/oa4mp-server-mysql.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  when: server_db is defined and server_db.changed

- name: create /etc/mysql file
  template:
    src: mysql.j2
    dest: /etc/mysql
    owner: root
    group: root
    mode: 0600

# perhaps not necessary but pretty harmless
- name: run mariadb-upgrade
  shell:
    cmd: . /etc/mysql && /usr/bin/mariadb-upgrade -u root --password=$PW
  no_log: true

- name: remove oa4mp server sql script
  file:
    path: /tmp/oa4mp-server-mysql.sql
    state: absent
  when: server_db is defined and server_db.changed
