---

# Install rsync

- name: install rsync packages
  yum: name={{item}} state=present
  with_items: "{{ rsync_packages }}"

# Setup rsync daemon for backups to outside

- name: configure rsyncd
  template:
    src: rsyncd.conf.j2
    dest: "/etc/rsyncd.conf"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes

- name: configure rsyncd secret
  template:
    src: rsyncd.secrets.j2
    dest: "/etc/rsyncd.secrets"
    owner: "root"
    group: "root"
    mode: 0600
  when: rsync_secret is defined

- name: configure xinetd to start rsync
  template:
    src: rsync.j2
    dest: "/etc/xinetd.d/rsync"
    owner: "root"
    group: "root"
    mode: 0644
