---

# Setup rsync daemon for backups to outside

- name: configure rsyncd 
  template:
    src: rsyncd.conf.j2
    dest: "/etc/rsyncd.conf"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes
  when: rsync_hosts is defined

- name: configure rsyncd secret
  template:
    src: rsyncd.secrets.j2
    dest: "/etc/rsyncd.secrets"
    owner: "root"
    group: "root"
    mode: 0600
  when: rsync_hosts is defined and rsync_secret is defined

- name: configure xinetd to start rsync
  template:
    src: rsync.j2
    dest: "/etc/xinetd.d/rsync"
    owner: "root"
    group: "root"
    mode: 0644
  when: rsync_hosts is defined
