---

# include tasks to execute

- include: hostname.yml
- include: sshd.yml
- include: epelrepo.yml
#- include: nikhefrepo.yml
- include: yum.yml
- include: network.yml
- include: iptables.yml
- include: access.yml
- include: ntpd.yml

# list of disabled services
# need to stop e.g. firewalld before starting iptables

- name: disable services 
  service: name={{ item }} state=stopped enabled=no
  with_items: "{{ disabled_services }}"

# list of enabled services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
