---

- name: get interface scripts
#  shell: "ls /sys/class/net/ | grep -v 'lo'"
  shell: "ls /etc/sysconfig/network-scripts/ifcfg-* | grep -v 'ifcfg-lo'"
  register: interfacescripts
  changed_when: false

- name: enable DHCPv6 on public DS interface
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ public_ds_interface }}"
    insertafter: "^IPV6INIT="
    regexp: "^DHCPV6C=.*"
    line: 'DHCPV6C="yes"'
    backup: yes
  notify: restart network
  when: inventory_hostname == groups.delegserver.0

- name: "disable network manager in {{ item }}"
  lineinfile:
    dest: "{{ item }}"
    regexp: "^NM_CONTROLLED=.*"
    line: "NM_CONTROLLED=no"
  notify: restart network
  with_items: "{{ interfacescripts.stdout_lines }}" 

# flush handlers in order to restart network as soon as ifcfg changes 
- meta: flush_handlers
