---
# Look for scripts for the existing non-loopback interfaces
- name: get interface scripts
  find:
    path: /etc/sysconfig/network-scripts
    pattern: "ifcfg-({{ ansible_interfaces | reject('equalto', 'lo') | join('|') }})$"
    use_regex: yes
  register: find_output

# Make list of their paths
- set_fact:
    interface_scripts: "{{ find_output.files | map(attribute='path') | list }}"

# Note that changing the way to get IPv6 might need expiring leases on server
# side, since (probably) the client-id will change
- name: enable DHCPv6 on public DS interface
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ public_ds_interface }}"
    regexp: "^DHCPV6C=.*"
    line: 'DHCPV6C="yes"'
    backup: yes
  notify: restart network
  when: inventory_hostname == groups.delegserver.0

- name: "disable network manager in {{ item }}"
  lineinfile:
    dest: "{{ item }}"
    regexp: "^NM_CONTROLLED=.*"
    line: "NM_CONTROLLED=no"
    backup: yes
  notify: restart network
  with_items: "{{ interface_scripts }}"

# flush handlers in order to restart network as soon as ifcfg changes
- meta: flush_handlers
