---

# custom sshd configuration

- name: raise sshd log level
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^LogLevel.*"
    line: "LogLevel VERBOSE"
    mode: 0600
    owner: root
    group: root
    backup: yes
  # sshd handler is defined in the common role
  notify: restart sshd

- name: disable ssh password logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication.*"
    line: "PasswordAuthentication no"
    mode: 0600
    owner: root
    group: root
    backup: yes
  # sshd handler is defined in the common role
  notify: restart sshd
