---

# First get netmask value using ipcalc
- name: get netmask from private_network
  shell: "ipcalc -m {{ private_network }}"
  register: private_network_netmask

- name: configure private interface
  template:
    src: ifcfg-private.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ private_ds_interface }}"
    owner: root
    group: root
    mode: 0644
  notify: restart network
  when:
    - not private_ds_interface == public_ds_interface
    - not private_ds_interface == "lo"
