---

- name: configure private interface
  template:
    src: ifcfg-private.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ private_ds_interface }}"
    owner: root
    group: root
    mode: 0644
  notify: restart network
  when:
    - not private_ds_interface == public_ds_interface
    - not private_ds_interface == "lo"

# flush handlers in order to restart network as soon as ifcfg changes: we need
# it to be up before we restart postfix!
- meta: flush_handlers
