---

### config private network

- import_tasks: ca-network.yml

### services required for backend CA

- import_tasks: dnsmasq.yml
- import_tasks: postfix.yml
- import_tasks: squid.yml
- import_tasks: ca-sshd.yml

### enable services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
