---

### config private network

- include: ca-network.yml

### services required for backend CA

- include: dnsmasq.yml
- include: postfix.yml
- include: squid.yml
- include: ca-sshd.yml

### enable services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
